import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hecasan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold">Hecasan Commerce</h1>
    </div>
  );
}
